### ISSUE TITLE
Is this mantained?

### ISSUE THREAD

**Issue by chepo92** [minimaldesign/instagram-widget#1]
I was looking for a simple gallery as to start with instagram, but i think this is not working I have set the auth token already but not loading any image

**Comment by minimaldesign** [comment]
I wrote this a while back for the home page of [this site](https://www.modernlivingsupplies.com) (the square on the top right) and it seems to still be working… 🤔

It's hard to help without any specific info… Are you getting any errors? Are you sure you're [targeting the right element](https://github.com/minimaldesign/instagram-widget/blob/master/instagram.js#L5) in your HTML?

Note that if you have some ad blockers setup, sometimes they will block instagram etc. depending on your settings…

**Comment by minimaldesign** [comment]
Closing for now. Feel free to submit more details…
